# -*- coding: utf-8 -*-
import numpy as np
from optparse import OptionParser
import yaml
    
def extract_dispersion(obj):

    nk = len(obj)
    nbands = len(obj[0]['band'])
    kdistances = np.zeros(nk)
    frequencies = np.zeros((nk, nbands))
    for ik in range(nk):
        kdistances[ik] = obj[ik]['distance']
        for ib in range(nbands):
            frequencies[ik][ib] = obj[ik]['band'][ib]['frequency']
    return kdistances, frequencies

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl.initialize import (set_matplot, set_axis, set_legend)

def plot_band(ks, fs, figname='fig_phband_phonopy.png', 
        dpi=300, fontsize=7, fig_width=2.8, aspect=0.7, lw=0.5, ms=2.0):
    
    set_matplot(fontsize=fontsize)
    fig = plt.figure(figsize=(fig_width, aspect*fig_width))
        
    ax = plt.subplot()
    ax.set_xlabel('')
    ax.set_ylabel('Frequency (${\\rm cm^{-1}}$)')
    
    nb = len(fs[0])
    for ib in range(nb):
        ax.plot(
                ks, fs[:,ib], linestyle='-', lw=lw, marker='None', 
                mfc='none', mew=lw
                )
    
    set_axis(ax)
    
    fig.savefig(figname, dpi=dpi, bbox_inches='tight')
    print(" Output", figname)
    return fig

def main(options):
    
    with open(options.filename) as file:
        obj = yaml.safe_load(file)

    ks, fs = extract_dispersion(obj['phonon'])

    plot_band(ks, fs)

    
if __name__ == '__main__':
    parser = OptionParser()
    
    parser.add_option("-f", "--filename", dest="filename", type="string",
            default="band.yaml", 
            help="band file generated by Phonopy [band.yaml]")
    
    (options, args) = parser.parse_args()
    main(options)

