
pw_keys = {
        'control':(
            ## string
            'calculation', 
            'title', 
            'restart_mode', 
            'verbosity', 
            'outdir', 
            'wfcdir', 
            'prefix', 
            'disk_io', 
            'pseudo_dir', 
            ## int
            'nstep', 
            'iprint', 
            'nberrycyc', 
            'gdir', 
            'nppstr', 
            ## bool
            'wf_collect', 
            'tstress', 
            'tprnfor', 
            'lkpoint_dir', 
            'tefield', 
            'dipfield', 
            'lelfield', 
            'lorbm', 
            'lberry', 
            'gate', 
            'lfcp', 
            'trism'
            ## float
            'dt', 
            'max_seconds', 
            'etot_conv_thr', 
            'forc_conv_thr', 
            ),
        'system':(
            ### int
            "ibrav", "nat", "ntyp", "nbnd",
            "nr1", "nr2", "nr3",
            "nr1s", "nr2s", "nr3s",
            "nspin",
            "nqx1", "nqx2", "nqx3",
            "edir",
            "report",
            "esm_nfit",
            "dftd3_version",
            "space_group",
            "origin_choice",
            ### real
            "celldm",
            "A", "B", "C",
            "cosAB", "cosAC", "cosBC",
            "tot_charge",
            "starting_charge",
            "tot_magnetization",
            "starting_magnetization",
            "ecutwfc", "ecutrho", "ecutfock",
            "degauss",
            "ecfixed",
            "qcutz",
            "q2sigma",
            "exx_fraction",
            "screening_parameter",
            "ecutvcut",
            "localization_thr",
            "emaxpos",
            "eopreg",
            "eamp",
            "fixed_magnetization",
            "lambda",
            "esm_w",
            "esm_efield",
            "gcscf_mu", "gcscf_conv_thr", "gcscf_beta",
            "london_s6", "london_c6", "london_rvdw", "london_rcut",
            "ts_vdw_econv_thr",
            "xdm_a1", "xdm_a2",
            "zgate",
            "block_1", "block_2", "block_height",
            ### real, array
            "Hubbard_occ", "Hubbard_alpha", "Hubbard_beta",
            "starting_ns_eigenvalue",
            "angle1", "angle2",
            ### bool
            "nosym",
            "nosym_evc",
            "noinv",
            "no_t_rev",
            "force_symmorphic",
            "use_all_frac",
            "noncolin",
            "ace",
            "x_gamma_extrapolation",
            "dmft",
            "ensemble_energies",
            "lforcet",
            "lspinorb",
            "lgcscf",
            "london",
            "dftd3_threebody",
            "ts_vdw_isolated",
            "xdm",
            "uniqueb",
            "rhombohedral",
            "relaxz",
            "block",
            ### string
            "occupations",
            "one_atom_occupations",
            "starting_spin_angle",
            "smearing",
            "input_dft",
            "exxdiv_treatment",
            "dmft_prefix",
            "constrained_magnetization",
            "assume_isolated",
            "esm_bc",
            "vdw_corr",
            ),
        'electrons': (
            "electron_maxstep",
            "scf_must_converge",
            "conv_thr",
            "adaptive_thr",
            "conv_thr_init",
            "conv_thr_multi",
            "mixing_mode",
            "mixing_beta",
            "mixing_ndim",
            "mixing_fixed_ns",
            "diagonalization",
            "diago_thr_init",
            "diago_cg_maxiter",
            "diago_ppcg_maxiter",
            "diago_david_ndim",
            "diago_rmm_ndim",
            "diago_rmm_conv",
            "diago_gs_nblock",
            "diago_full_acc",
            "efield",
            "efield_cart",
            "efield_phase",
            "startingpot",
            "startingwfc",
            "tqr",
            "real_space",
            ),
        'ions': (
            "ion_positions",
            "ion_velocities",
            "ion_dynamics",
            "pot_extrapolation",
            "wfc_extrapolation",
            "remove_rigid_rot",
            "ion_temperature",
            "tempw",
            "tolp",
            "delta_t",
            "nraise",
            "refold_pos",
            "upscale",
            "bfgs_ndim",
            "trust_radius_max",
            "trust_radius_min",
            "trust_radius_ini",
            "w_1",
            "w_2",
            "fire_alpha_init",
            "fire_falpha",
            "fire_nmin",
            "fire_f_inc",
            "fire_f_dec",
            "fire_dtmax",
            ),
        'cells': (
            "cell_dynamics",
            "press",
            "wmass",
            "cell_factor",
            "press_conv_thr",
            "cell_dofree",
                ),
        'fcp':(
            "fcp_mu",
            "fcp_dynamics",
            "fcp_conv_thr",
            "fcp_ndiis",
            "fcp_mass",
            "fcp_velocity",
            "fcp_temperature",
            "fcp_tempw",
            "fcp_tolp",
            "fcp_delta_t",
            "fcp_nraise",
            "freeze_all_atoms",
            ),
        'rism':(
            "nsolv",
            "closure",
            "tempv",
            "ecutsolv",
            "solute_lj",
            "solute_epsilon",
            "solute_sigma",
            "starting1d",
            "starting3d",
            "smear1d",
            "smear3d",
            "rism1d_maxstep",
            "rism3d_maxstep",
            "rism1d_conv_thr",
            "rism3d_conv_thr",
            "mdiis1d_size",
            "mdiis3d_size",
            "mdiis1d_step",
            "mdiis3d_step",
            "rism1d_bond_width",
            "rism1d_dielectric",
            "rism1d_molesize",
            "rism1d_nproc",
            "rism3d_conv_level",
            "rism3d_planar_average",
            "laue_nfit",
            "laue_expand_right",
            "laue_expand_left",
            "laue_starting_right",
            "laue_starting_left",
            "laue_buffer_right",
            "laue_buffer_left",
            "laue_both_hands",
            "laue_wall",
            "laue_wall_z",
            "laue_wall_rho",
            "laue_wall_epsilon",
            "laue_wall_sigma",
            "laue_wall_lj6",
            ),
        }

